
### login
POST http://localhost:8080/auth/login
Content-Type:  application/json

{
  "email": "mukhtarovsarvarbek@gmail.com",
  "password": "12341234"
}

### registration
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Sarvar",
  "surname": "Muxtarov",
  "email": "mukhtarovsarvarbek@gmail.com",
  "password": "12345678"
}

###
POST https://mykun-uz.herokuapp.com/auth/login
Content-Type:  application/json

{
  "email": "mukhtarovsarvarbek@gmail.com",
  "password": "sar123"
}


