
### login
POST https://appkunuz.herokuapp.com/auth/login
Content-Type:  application/json

{
  "email": "mukhtarovsarvarbek@gmail.com",
  "password": "12345678"
}

### registration
POST  https://appkunuz.herokuapp.com/auth/registration
Content-Type: application/json

{
  "name": "Javlon",
  "surname": "Abdurakhmanov",
  "email": "abdurakhmanovjb@icloud.com",
  "password": "12345678"
}

###
POST https://mykun-uz.herokuapp.com/auth/login
Content-Type:  application/json

{
  "email": "mukhtarovsarvarbek@gmail.com",
  "password": "sar123"
}


